"""rename address

Revision ID: 38150ee3bc8b
Revises: c9930afdca64
Create Date: 2024-07-01 22:13:53.806469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38150ee3bc8b'
down_revision = 'c9930afdca64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
